#ifndef DECLARACIONOPCIONESMAPAMESAS_H_INCLUDED
#define DECLARACIONOPCIONESMAPAMESAS_H_INCLUDED

void seleccionarTipoPedido();
void mostrarPantallaPedidos();

#endif // DECLARACIONOPCIONESMAPAMESAS_H_INCLUDED
