#ifndef DECLARACIONOPCIONESCONFIGURACIONES_H_INCLUDED
#define DECLARACIONOPCIONESCONFIGURACIONES_H_INCLUDED

void mostrarConfigurarCarta();
void mostrarEmpleados();

#endif // DECLARACIONOPCIONESCONFIGURACIONES_H_INCLUDED
